In [1]:
# Dependencies
import requests
import json
import quandl
import pandas as pd
from config import price_key

In [4]:
# URL for GET requests to retrieve vehicle data
tickers = ['IVZ','GM','UAA''WFC','TWTR','SBUX','CRM','AMZN','GE','CMG']
mydata = GET https://api.worldtradingdata.com/api/v1/history?symbol=tickers&sort=newest&api_token=price_key

SyntaxError: invalid syntax (<ipython-input-4-81765e43d6b4>, line 3)

In [11]:
df = pd.DataFrame(mydata)
mydata

     ticker       date    close      volume
None
0      TWTR 2018-03-27    28.07  79821992.0
1      TWTR 2018-03-26    31.91  25477813.0
2      TWTR 2018-03-23    31.03  24478532.0
3      TWTR 2018-03-22    31.20  29284239.0
4      TWTR 2018-03-21    32.73  43359002.0
5      TWTR 2018-03-20    31.35  82222740.0
6      TWTR 2018-03-19    34.98  22116551.0
7      TWTR 2018-03-16    35.58  13747877.0
8      TWTR 2018-03-15    35.80  20921849.0
9      TWTR 2018-03-14    36.60  39409327.0
10     TWTR 2018-03-13    34.11  21967251.0
11     TWTR 2018-03-12    35.50  20963776.0
12     TWTR 2018-03-09    35.35  18513795.0
13     TWTR 2018-03-08    34.85  24764968.0
14     TWTR 2018-03-07    35.76  33656143.0
15     TWTR 2018-03-06    34.43  22592276.0
16     TWTR 2018-03-05    34.58  34839998.0
17     TWTR 2018-03-02    33.00  24918891.0
18     TWTR 2018-03-01    32.24  25032477.0
19     TWTR 2018-02-28    31.86  24101591.0
20     TWTR 2018-02-27    31.32  16464903.0
21     TWTR 2018-02-26    32.16  15742166.0
22     TWTR 2018-02-23    32.66  17252683.0
23     TWTR 2018-02-22    32.11  29128051.0
24     TWTR 2018-02-21    33.38  29431220.0
25     TWTR 2018-02-20    32.84  22677763.0
26     TWTR 2018-02-16    33.06  27626996.0
27     TWTR 2018-02-15    33.61  31921343.0
28     TWTR 2018-02-14    33.75  38842195.0
29     TWTR 2018-02-13    33.44  56959420.0
...     ...        ...      ...         ...
442    AMZN 2018-02-13  1414.51   5858860.0
443    AMZN 2018-02-12  1386.23   6682214.0
444    AMZN 2018-02-09  1338.99  13787886.0
445    AMZN 2018-02-08  1350.47   8108560.0
446    AMZN 2018-02-07  1416.78   7066828.0
447    AMZN 2018-02-06  1442.84  10773963.0
448    AMZN 2018-02-05  1396.62  10756332.0
449    AMZN 2018-02-02  1431.00  10915962.0
450    AMZN 2018-02-01  1390.00   7812953.0
451    AMZN 2018-01-31  1451.65   6220396.0
452    AMZN 2018-01-30  1437.82   5736512.0
453    AMZN 2018-01-29  1417.68   5628992.0
454    AMZN 2018-01-26  1402.05   4584082.0
455    AMZN 2018-01-25  1377.95   4621862.0
456    AMZN 2018-01-24  1357.51   6730084.0
457    AMZN 2018-01-23  1362.54   5056764.0
458    AMZN 2018-01-22  1327.31   3970151.0
459    AMZN 2018-01-19  1294.58   4395070.0
460    AMZN 2018-01-18  1293.32   3941007.0
461    AMZN 2018-01-17  1295.00   5166748.0
462    AMZN 2018-01-16  1304.86   7111172.0
463    AMZN 2018-01-12  1305.20   5360681.0
464    AMZN 2018-01-11  1276.68   3075315.0
465    AMZN 2018-01-10  1254.33   2659507.0
466    AMZN 2018-01-09  1252.70   3646681.0
467    AMZN 2018-01-08  1246.87   4177533.0
468    AMZN 2018-01-05  1229.14   3430148.0
469    AMZN 2018-01-04  1209.59   3000366.0
470    AMZN 2018-01-03  1204.20   3044664.0
471    AMZN 2018-01-02  1189.01   2587899.0

[472 rows x 4 columns]

In [6]:
df.to_csv('../../db/ticker_closing_prices.csv', sep=',')