In [47]:
import pandas as pd
import pandas_datareader as web
import datetime
import numpy as np

In [48]:
df = pd.read_csv('../../db/SP_Tickers.csv',header=None,sep=',')
df
chosen_stocks = np.random.choice(500, replace=False, size=100)
df_trimmed = df.loc[chosen_stocks]
df_trimmed

        0
475  VRTX
152     D
486  WELL
351  ORCL
341  NTRS
401   RCL
391   REG
172   EQT
115   CFG
454   TSN
140   DVA
170  EVHC
403   CRM
296   MMC
83   BF.B
467   UNM
54    ADM
169   ETR
405   SCG
372    PX
129   GLW
76   BKNG
399   ROP
456   UDR
304   MDT
321   MSI
95   CBRE
328  NFLX
297   MLM
45   ANDV
..    ...
157   DUK
299    MA
440   MOS
447   TMK
228  HSIC
171   EOG
480   WMT
470   VAR
306   MET
124   CAG
4     ACN
144   DVN
471   VTR
331   NEM
330   NFX
66    BAC
111  CINF
290   MTB
62    AVB
472  VRSN
99    CNP
273   KSS
445   TWX
52   AMAT
324   NOV
283   LLY
292     M
295   MAR
16    ALK
377   PRU

[100 rows x 1 columns]

In [49]:
df_trimmed.to_csv('../../db/hundred_addl_stocks.csv')