In [2]:
# Dependencies
import requests
import json
import quandl
import pandas as pd
from config import qkey

In [3]:
# URL for GET requests to retrieve vehicle data
quandl.ApiConfig.api_key = qkey
tickers = ['IVZ','GM','UAA''WFC','TWTR','SBUX','CRM','AMZN','GE','CMG']
mydata = quandl.get_table('WIKI/PRICES', qopts = { 'columns': ['ticker', 'date', 'close'] }, ticker = tickers, date = { 'gte': '2018-01-01', 'lte': '2019-11-10' })

In [4]:
df = pd.DataFrame(mydata)
mydata

     ticker       date    close
None
0      TWTR 2018-03-27    28.07
1      TWTR 2018-03-26    31.91
2      TWTR 2018-03-23    31.03
3      TWTR 2018-03-22    31.20
4      TWTR 2018-03-21    32.73
5      TWTR 2018-03-20    31.35
6      TWTR 2018-03-19    34.98
7      TWTR 2018-03-16    35.58
8      TWTR 2018-03-15    35.80
9      TWTR 2018-03-14    36.60
10     TWTR 2018-03-13    34.11
11     TWTR 2018-03-12    35.50
12     TWTR 2018-03-09    35.35
13     TWTR 2018-03-08    34.85
14     TWTR 2018-03-07    35.76
15     TWTR 2018-03-06    34.43
16     TWTR 2018-03-05    34.58
17     TWTR 2018-03-02    33.00
18     TWTR 2018-03-01    32.24
19     TWTR 2018-02-28    31.86
20     TWTR 2018-02-27    31.32
21     TWTR 2018-02-26    32.16
22     TWTR 2018-02-23    32.66
23     TWTR 2018-02-22    32.11
24     TWTR 2018-02-21    33.38
25     TWTR 2018-02-20    32.84
26     TWTR 2018-02-16    33.06
27     TWTR 2018-02-15    33.61
28     TWTR 2018-02-14    33.75
29     TWTR 2018-02-13    33.44
...     ...        ...      ...
442    AMZN 2018-02-13  1414.51
443    AMZN 2018-02-12  1386.23
444    AMZN 2018-02-09  1338.99
445    AMZN 2018-02-08  1350.47
446    AMZN 2018-02-07  1416.78
447    AMZN 2018-02-06  1442.84
448    AMZN 2018-02-05  1396.62
449    AMZN 2018-02-02  1431.00
450    AMZN 2018-02-01  1390.00
451    AMZN 2018-01-31  1451.65
452    AMZN 2018-01-30  1437.82
453    AMZN 2018-01-29  1417.68
454    AMZN 2018-01-26  1402.05
455    AMZN 2018-01-25  1377.95
456    AMZN 2018-01-24  1357.51
457    AMZN 2018-01-23  1362.54
458    AMZN 2018-01-22  1327.31
459    AMZN 2018-01-19  1294.58
460    AMZN 2018-01-18  1293.32
461    AMZN 2018-01-17  1295.00
462    AMZN 2018-01-16  1304.86
463    AMZN 2018-01-12  1305.20
464    AMZN 2018-01-11  1276.68
465    AMZN 2018-01-10  1254.33
466    AMZN 2018-01-09  1252.70
467    AMZN 2018-01-08  1246.87
468    AMZN 2018-01-05  1229.14
469    AMZN 2018-01-04  1209.59
470    AMZN 2018-01-03  1204.20
471    AMZN 2018-01-02  1189.01

[472 rows x 3 columns]

In [9]:
df.to_csv('ticker_closing_prices.csv', sep=',')